### ISSUE TITLE
Repo should be more "open source" friendly

### ISSUE THREAD

**Issue by gaieges** [IntuitionMachines/redis-tools#5]
Since we opened sourced this repo, it's widely available to all.  At the moment I don't think we really treat it that way so jotting down some things that would help make it more so:

- Tests
- CI / CD build tasks (ie push to PyPi with increment of version)
- More docs and well-defined API for components (ie RedisList, dump_utils don't have much).  Additionally: on changes as well.
- Break out components from `__init__.py` (should just do module global stuff)
- Ensuring that reviewers keep hmt specific stuff out of this repo

**Comment by posix4e** [comment]
can you close this and make 5 issues?

**Comment by gaieges** [comment]
Yah, not all of these are actionable though (specifically the last one)
